# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
