# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20170830_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shipped', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.Buyer')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.Cart')),
            ],
        ),
    ]
